### ISSUE TITLE
Template does not save.

### ISSUE THREAD

**Issue by WPDevHQ** [jubstuff/templates-from-plugin#1]
Hey,

A simple and clean aproach.

Unfortunatelly the template when selected does not save - upon publish/update the meta box reverts to default template.

**Comment by jubstuff** [comment]
Thank you @WPDevHQ . I'll take a look at this

**Comment by jubstuff** [comment]
Hi @WPDevHQ ,

I was not able to replicate the issue. 

I created a new page and the meta box retained the correct value. The same occurred upon update.

I'm going to close the issue for now, but please feel free to reopen it with the exact steps to reproduce the issue.
